mongodb:
  uri: CHANGE ME
  db_name: Juggler
  collections:
    users: Users
    orders: Orders
    resources:
      stations: Stations
      crawler_routes: CrawlerRoutes
      pandemic_routes: PandemicRoutes
      rts: RTS

jwt_tokens:
  secret_key: bn2W1MTOHFsHtZssUX3sCAxVinH9X0ad
  algorithm: HS256
  access_token_expire_minutes: 60