mongodb:
  uri: CHANGE ME
  db_name: Juggler
  collections:
    users: Users
    orders: Orders
    stations: Stations
    crawler_routes: CrawlerRoutes
    pandemic_routes: PandemicRoutes
    rts: RTS